## NumPy

- 고성능 Array 처리 라이브러리

numpy 설치

In [1]:
!pip install numpy

textract 1.6.1 has requirement chardet==2.3.0, but you'll have chardet 3.0.4 which is incompatible.
spyder-kernels 0.2.6 has requirement ipykernel>=4.8.2, but you'll have ipykernel 4.8.1 which is incompatible.
spyder-kernels 0.2.6 has requirement jupyter-client>=5.2.3, but you'll have jupyter-client 5.2.2 which is incompatible.
spyder-kernels 0.2.6 has requirement pyzmq>=17, but you'll have pyzmq 16.0.4 which is incompatible.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np

In [4]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
data + data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### n-d array (matrix) 계산에 유용하게 사용 가능하다

In [17]:
data =  [[0,1,2], [3,4,5], [6,7,8]]

data

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [12]:
arr = np.array(data)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [16]:
# 만약 python이라면...
data2 = []

for row in data:
    new_row = []
    for cell in row:
        new_row.append(cell*2)
    data2.append(new_row)

data2

[[0, 2, 4], [6, 8, 10], [12, 14, 16]]

In [21]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [22]:
arr.dtype

dtype('int64')

In [27]:
arr.astype('uint8')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=uint8)

In [24]:
# 여러 종류의 타입 포함 가능
np.array([1, 2.3, '4'])

array(['1', '2.3', '4'], dtype='<U32')