## NumPy

- 고성능 Array 처리 라이브러리

numpy 설치

In [2]:
!pip install numpy

textract 1.6.1 has requirement chardet==2.3.0, but you'll have chardet 3.0.4 which is incompatible.
spyder-kernels 0.2.6 has requirement ipykernel>=4.8.2, but you'll have ipykernel 4.8.1 which is incompatible.
spyder-kernels 0.2.6 has requirement jupyter-client>=5.2.3, but you'll have jupyter-client 5.2.2 which is incompatible.
spyder-kernels 0.2.6 has requirement pyzmq>=17, but you'll have pyzmq 16.0.4 which is incompatible.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
data + data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### n-d array (matrix) 계산에 유용하게 사용 가능하다

- python에서 리스트에 활용할 수 있는 함수들과 비교하는 것이 중요하다. (동일한 함수 형태지만 기능이 다음)

In [15]:
data =  [[0,1,2], [3,4,5], [6,7,8]]

data

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

### 배열 생성

In [30]:
arr = np.array(data)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# 쉽게 0, 1에 대한 배열 생성하기
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr.shape

(3, 3)

### 배열 연산

In [20]:
# python에서 리스트에 곱을 하면
[0, 2, 4] * 2

[0, 2, 4, 0, 2, 4]

In [21]:
# 하지만 numpy에서는
arr * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [23]:
# 만약 python을 통해 위의 계산을 진행하려면...
data2 = []

for row in data:
    new_row = []
    for cell in row:
        new_row.append(cell*2)
    data2.append(new_row)

data2

[[0, 2, 4], [6, 8, 10], [12, 14, 16]]

In [11]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

### 배열 자료형

In [25]:
# 배열에 저장된 자료형을 알려주는 객체
arr.dtype

dtype('int64')

#### 배열 자료형 변환

In [31]:
arr.astype('uint8')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=uint8)

In [32]:
np.array(['1.25', '2.45', '0.9']).astype('float')

array([1.25, 2.45, 0.9 ])

In [14]:
# 여러 종류의 타입 포함 가능
np.array([1, 2.3, '4'])

array(['1', '2.3', '4'], dtype='<U32')

### 슬라이싱

- 파이썬의 리스트와 유사하게 동작한다

In [34]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr[5:8]

array([5, 6, 7])

In [37]:
# 선택 영역 전체 수정
arr[5:8] = 99
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 배열 조각(슬라이스)는 원본 배열의 뷰이다. 
- 뷰에 대한 변경은 그대로 원본에 반영된다.

In [46]:
slice_1 = arr[0:2]
slice_1[:] = 100
arr

array([100, 100,   2,   3,   4,  99,  99,  99,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

#### 만약 뷰 대신 복사본을 얻고 싶다면 .copy()를 활용해야한다.

In [49]:
slice_2 = arr[10:12].copy()
slice_2[:] = 100
slice_2

array([100, 100])

In [50]:
arr

array([100, 100,   2,   3,   4,  99,  99,  99,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

### 다차원 배열 인덱스

In [52]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2[0]

array([1, 2, 3])

#### 개별 요소는 재귀적으로 접근한다
#### , 로 구분된 색인 리스트 활용도 가능하다


|   | 0 | 1 | 2 |
|---|---|---|---|
| 0 | 0,0 | 0,1 | 0,2 |
| 1 | 1,0 | 1,1| 1,2 |
| 2 | 2,0 | 2,1| 2,2 |

In [56]:
arr2[1][0]

4

In [57]:
arr2[1,0]

4