In [1]:
import numpy as np

# 파이썬 리스트 연산

In [2]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
data + data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# numpy

In [4]:
data = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
]

In [5]:
data

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [6]:
np.array(data)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
arr = np.array(data)

In [10]:
arr.shape

(3, 3)

In [11]:
data

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

## 배열 연산

In [12]:
arr * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
arr.dtype

dtype('int64')

In [17]:
arr = arr.astype('uint8')

In [18]:
arr.dtype

dtype('uint8')

## 슬라이싱

In [19]:
arr = np.arange(20)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arr[5:8]

array([5, 6, 7])

In [27]:
slice1 = arr[5:8]

In [28]:
slice1

array([5, 6, 7])

In [29]:
slice1[:] = 99

In [30]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
slice2 = arr[5:8].copy()

In [32]:
slice2

array([99, 99, 99])

In [33]:
slice2[:] = 100

In [34]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# column, row, cell

In [38]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [39]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2[0]

array([1, 2, 3])

In [41]:
arr2[0][1]

2

In [42]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
arr[arr >10]

array([99, 99, 99, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## 형태 변환

In [44]:
arr = np.arange(9)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
arr.shape

(9,)

In [49]:
arr = arr.reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr.ndim

2

In [51]:
arr.reshape(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
%timeit [n * 1.1 for n in [1,2,3,4,5,6,7,8,9]]

735 ns ± 22.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
